---

# Ceedling configuration file.
# Copyright (c) 2015, Diego Asanza. All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301  USA
#
# Created on October 10, 2016, 10:08 PM
#
# Adjust according to your setup.
# We use the microchip toolchain. For the unit tests the mdb (microchip
# debugger) is necessary. For command line programming the ipecmd (microchip
# ipe tool) is needed.
#

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: FALSE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_

:environment:
  - :mcu: 18F4550 # choose your processor
  - :path:
    - /bin
    - /usr/bin  # path for rake (ruby make)
    - /opt/microchip/xc8/v1.37/bin  # path to xc8 compiler
    - /opt/microchip/mplabx/v3.30/mplab_ide/bin # path to the mdb executable.
    - /opt/microchip/mplabx/v3.30/mplab_ipe # path to the ipecmd executable.

:extension:
  :executable: .out
  :object: .p1

:release_build:
  :output: gpib2usb
  :use_assembly: TRUE

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :support:
    - test/support
  :include:
    - "/opt/microchip/xc8/v1.37/include"  # path to microchip libraries

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :commmon: &common_defines []
  :release:
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :defines:
    - CMOCK_MEM_SIZE=256
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

:tools:
  :test_compiler:
    :executable: xc8
    :arguments:
      - --pass1
      - --chip=#{ENV['MCU']}
      - -Q
      - -G
      - --double=24
      - --float=24
      - --emi=wordwrite
      - --opt=default,+asm,+asmfile,-speed,+space,-debug
      - --addrqual=ignore
      - --mode=free
      - -P
      - -N255
      - --warn=0
      - --asmlist
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - --summary=default,-psect,-class,+mem,-hex,-file
      - --output=default,-inhx032
      - --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib
      - --output=-mcof,+elf:multilocs
      - --stack=compiled:auto:auto:auto
      #- "--errformat=%f:%l: error: (%n) %s"
      #- "--warnformat=%f:%l: warning: (%n) %s"
      #- "--msgformat=%f:%l: advisory: (%n) %s"
      - -o"${2}"
      - "${1}"

  :test_linker:
    :executable: xc8
    :arguments:
      - --chip=#{ENV['MCU']}
      - -G
      - -m"./build/test/TestBuild.map"
      - --double=24
      - --float=24
      - --emi=wordwrite
      - --opt=default,+asm,+asmfile,-speed,+space,-debug
      - --addrqual=ignore --mode=free -P -N255
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - --warn=0
      - --asmlist
      - --summary=default,-psect,-class,+mem,-hex,-file
      - --output=default,-inhx032
      - --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib
      - --output=-mcof,+elf:multilocs
      - --stack=compiled:auto:auto:auto
      #- "--errformat=%f:%l: error: (%n) %s"
      #- "--warnformat=%f:%l: warning: (%n) %s"
      #- "--msgformat=%f:%l: advisory: (%n) %s"
      - --memorysummary "./build/test/memoryfile.xml"
      - -o"./build/test/TestBuild.elf"
      - "${1}"

  :test_fixture:
    :executable: ruby
    :name: "XC8 Test Fixture"
    :stderr_redirect: :unix # win inform Ceedling what model of $stderr capture to use
    :arguments:
      - test/support/sim_test_fixture.rb

  :release_compiler:
    :executable: xc8
    :arguments:
      - --pass1
      - --chip=#{ENV['MCU']}
      - -Q
      - -G
      - --double=24
      - --float=24
      - --emi=wordwrite
      - --opt=default,+asm,+asmfile,-speed,+space,-debug
      - --addrqual=ignore
      - --mode=free
      - -P
      - -N255
      - --warn=0
      - --asmlist
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -DREPOVERSION=\\\"#{`git describe --abbrev=4 --dirty --always|tr -d '\n'`}\\\"
      - -DREPOBRANCH=\\\"#{`git rev-parse --abbrev-ref HEAD|tr -d '\n'`}\\\"
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - --summary=default,-psect,-class,+mem,-hex,-file
      - --output=default,-inhx032
      - --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib
      - --output=-mcof,+elf:multilocs
      - --stack=compiled:auto:auto:auto
      #- "--errformat=%f:%l: error: (%n) %s"
      #- "--warnformat=%f:%l: warning: (%n) %s"
      #- "--msgformat=%f:%l: advisory: (%n) %s"
      - -o"${2}"
      - "${1}"

  :release_linker:
    :executable: xc8
    :arguments:
      - --chip=#{ENV['MCU']}
      - -G
      - -m"./build/test/TestBuild.map"
      - --double=24
      - --float=24
      - --emi=wordwrite
      - --opt=default,+asm,+asmfile,-speed,+space,-debug
      - --addrqual=ignore --mode=free -P -N255
      - -D$: COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - --warn=0
      - --asmlist
      - --summary=default,-psect,-class,+mem,-hex,-file
      - --output=default,-inhx032
      - --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,+plib
      - --output=-mcof,+elf:multilocs
      - --stack=compiled:auto:auto:auto
      #- "--errformat=%f:%l: error: (%n) %s"
      #- "--warnformat=%f:%l: warning: (%n) %s"
      #- "--msgformat=%f:%l: advisory: (%n) %s"
      - --memorysummary "./build/release/memoryfile.xml"
      - -o"./build/release/gpib2usb.elf"
      - "${1}"


:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
...
